### ISSUE TITLE
Accessing degreeIn of a node in an empty graph segfaults.

### ISSUE THREAD

**Issue by jfrog-tamirb** [networkit/networkit#1007]
When I run the following code:

```python
import networkit as nk
nk.Graph().degreeIn(0)
```

With:
- Networkit 10.0
- The Python:3.10 docker image, or Windows

I get a segfault:
```
root@8e2595a8e77c:/# python
Python 3.10.5 (main, Jun 23 2022, 10:42:52) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import networkit as nk
<frozen importlib._bootstrap>:241: ReducedFunctionalityWarning: WARNING: module 'pandas' not found, some functionality will be restricted
>>> nk.Graph().degreeIn(0)
Segmentation fault
```

This seems to be the case for many operations or queries. 
It seems odd when other operations, like `Graph.addEdge`, raise an exception if a node is missing.

When writing in Python, I'd expect all operations to be bounds-checked, and raise exceptions if they fail.

If this is not the case - is there a general rule to follow as to which operations are bounds-checked and which are not?

**Comment by fabratu** [comment]
Thanks for reaching out.

In general we omit checks for performance critical functions (if the check is itself is costly). However this is normally included in the documentation.

Concerning your issue: Functions which include acces to a node, should always include an existience check (since it is cheap). As for `degreeIn` and related functions, this is missing and therefore a bug. Will fix this.

A temp. workaround would be to call `G.hasNode(u)`[1] before calling `degreeIn`.

[1] https://networkit.github.io/dev-docs/python_api/graph.html?highlight=hasnode#networkit.graph.Graph.hasNode

**Comment by fabratu** [comment]
Based on a discussion in #1058 we did not include a check in `degreeIn` since it is not so cheap if used repeatedly (which is the case for many algorithms). Also, from a design perspective - in order to maintain the high throughput and speed and NetworKit - sanity checks are for most parts disabled in the release package.

If you need to access neighbors of a node, which might be present or not, calling `G.hasNode(u)` is likely the best workaround.

Will close this issue for now. Feel free to reopen it if there are any more questions.
