### ISSUE TITLE
How to calculate JaccardDistance in Python?

### ISSUE THREAD

**Issue by j-adamczyk** [networkit/networkit#1025]
Is it possible to calculate JaccardDistance in Python version of Networkit? It requires list of edge triangle counts, but I could not find how to compute this in the Python version. It is also not covered by examples in Jupyter Notebooks.

**Comment by fabratu** [comment]
Hi (and thanks for your patience!),

you can get the triangle count via `nk.sparsification.TriangleEdgeScore(G).run().scores()`. However, after looking at the code, it seems that the `JaccardDistance` is currently a broken feature in NetworKit (at least for the Python side). 

It is among the oldest code and is also not involved in any unit tests. A few changes won't cut it here, because the implementation needs an overhaul. Will try to create a PR shortly, so that the feature will again work in the upcoming release.

**Comment by j-adamczyk** [comment]
@fabratu I suspected so, thanks for confirmation. However, Jaccard Index seems to work just fine. What exactly is the difference between those two?

**Comment by fabratu** [comment]
You mean from the perspective of implementation or from the perspective of definition?

For the implementation, they use different aspect formulas:

- Index for node u, v: `N_common(u,v) / N_union(u, v)`
- Distance for edge e connecting node u, v: `1-triangle_count(e)/(degree(u)+degree(v)-triangle_count(e))

For the definition, both values are related by J_dist = 1 - J_index.

Your observation (one functioning, while the other doesn't) is also part of the reason why the implementation of the distance needs an overhaul.

**Comment by j-adamczyk** [comment]
@fabratu I thought so, thank you for fast answer. Indeed having two implementations is weird in this situation, especially since calculation of Jaccard Index should be faster (at least based on my intuition and those formulas). I am looking forward for those fixes.
