### ISSUE TITLE
nk.community.kCoreCommunityDetection error

### ISSUE THREAD

**Issue by yushangdi** [networkit/networkit#1070]
I'm trying to run nk.community.kCoreCommunityDetection, and got an error AttributeError: 'networkit.centrality.CoreDecomposition' object has no attribute 'cores'. It seems that this line https://github.com/networkit/networkit/blob/master/networkit/community.pyx#L1847 is not valid anymore?

**Comment by clstaudt** [comment]
Hi @fabratu, I am the developer behind the [trIAge project](https://github.com/trIAgelab/trIAge) which is developing an AI assistant to make life easier for open source communities. 

I am currently exploring how the bot performs on real-world issues and how much context it needs to be supplied with to solve them. I hope you don't mind the direct approach, but NetworKit is a great test case because I am a former maintainer who is not actively working on the project anymore. Generating this response still involved some manual steps that we are currently trying to validate and automate. 

I'd appreciate your feedback, especially whether the bot response solves the issue, and you would consider accepting a pull request from the trIAge bot in the future.

**Comment by fabratu** [comment]
@clstaudt Nice tool, this might indeed help both users in using the software as also developers in improving the API. Will try to give feedback wherever possible. What kind of PRs can we expect from trIAge?

Answer to the issue:

The problem here is a mere typo. It should be `scores()` not `cores()`. While retrieving the cover is also a solution, the canonical way is to use `scores()` for centrality measures. You can see an example of how to use it here: https://networkit.github.io/dev-docs/notebooks/User-Guide.html#Core-Decomposition

We currently test the code, however the test is misleading and therefore does not detect erroneous behavior. The doc string is also not complete - all in all time to refresh the code. If possible, maybe you can post a PR fixing this issue? If not, we will schedule a fix. In the time being, as a workaround, you can call the included calls on your own.

**Comment by clstaudt** [comment]
@fabratu 

> The problem here is a mere typo. It should be scores() not cores()

Interesting, the model came up with a correct solution but not the preferred solution.

> What kind of PRs can we expect from trIAge?

How can an LLM like GPT4 assist, given it has access to the code base and the documentation? In the first steps we want to provide a GitHub bot with assistance capabilities, e.g. suggest how to improve the way the issue was reported, detect when the question has already been answered in the documentation, generate test cases for the reported issue, suggest bugfixes and other solutions... The goal is to take workload from maintainers and provide faster support to users. Automated creation of Pull Requests that fix issues may not be too far in the future.

**Comment by clstaudt** [comment]
@fabratu  If I am not mistaken the first solution is actually the better one.

**Comment by yushangdi** [comment]
@fabratu @clstaudt Thanks! I tried the following code taken from the chat history:

`# Create an empty graph
graph = nk.Graph()

# Add nodes to the graph
graph.addNode()  # Node 0
graph.addNode()  # Node 1
graph.addNode()  # Node 2

# Add edges to form a triangle
graph.addEdge(0, 1)  # Edge from node 0 to node 1
graph.addEdge(1, 2)  # Edge from node 1 to node 2
graph.addEdge(2, 0)  # Edge from node 2 to node 0


coreDec = nk.centrality.CoreDecomposition(graph)
coreDec.run()
cores = coreDec.scores()
k = 1
try:
    kCore = [index for index, score in enumerate(cores) if score >= k]
except IndexError:
    raise RuntimeError("There is no core for the specified k")
print(kCore)

C = nk.graph.Subgraph().fromNodes(graph, kCore)	# FIXME: node indices are not preserved`

but got error "AttributeError: module 'networkit.graph' has no attribute 'Subgraph'". What should I fix?

**Comment by yushangdi** [comment]
seems that subgraphFromNodes has another API now. I made a version that works for me. https://github.com/networkit/networkit/pull/1096
