### ISSUE TITLE
Windows binaries. How much could be difficult? 

### ISSUE THREAD

**Issue by nico1996it** [networkit/networkit#195]
I really need to build the windows binaries of this library, but before trying, I ask you if it could be trivial or not. 
Because i saw that there's not strange dependencies or anything like that, and so I'm thinking about why there's no official binaries.
Thanks

**Comment by avdgrinten** [comment]
The main reason why Windows binaries do not exist is because none of the maintainers uses Windows. There were some attempts to make NetworKit run on Windows but they did not make it to a full PR.

Regarding the code: Yes, there are no strange libraries, so porting NetworKit to Windows should not be too hard. Some classes use Linux specific functions but I do not think it would be much work to add Windows-specific workarounds. Work is underway to switch to cmake as a build system which is able to generate Visual Studio projects. This should make it much more easy to build NetworKit on Windows.

However, instead of porting NetworKit directly to Windows, you might want to consider using WSL. Could you tell us more about your exact use case and why it is necessary to build the library on Windows?

**Comment by avdgrinten** [comment]
It would be acceptable to have a Windows port with some missing/disabled features first. Once we have that, we could iteratively fix all features. If you have code cleanups to make the code more conforming to C++ standards, you could also post that as a separate PR before posting the full Windows support.

In my opinion a critical feature regarding Windows support would be CI for Windows. This would prevent us from breaking Windows support in the future even if we do not primarily develop on Windows. Unfortunately, Travis does not support this; however, other CI services (like AppVeyor) do.

**Comment by manpen** [comment]
I will try to filter standard-related issues, but there are only a few. 
Regarding failing tests: I will look at them more detailed, and if there something a cannot fix quickly I will disable the feature. I few implementations will be less efficient, since omp task is not supported by MSVC. Hence I disabled parallelism there, which could be fixed using explicit task queues (as included in TLX), but I currently do not see the point.
AppVeyor is already implemented.

**Comment by fabratu** [comment]
Closing this issue, since Windows binaries are supported by now.
