### ISSUE TITLE
UserGuide notebook not found

### ISSUE THREAD

**Issue by alvarodemig** [networkit/networkit#280]
I get a 404 message when I try to open the UserGuide:
(http://nbviewer.jupyter.org/urls/networkit.github.io/uploads/docs/NetworKit_UserGuide.ipynb)

404 : Not Found
You are requesting a page that does not exist!
The remote resource was not found.

Same issue with any of the provided guides

**Comment by AlexMRuch** [comment]
Yeah, I've found that most of the links on the website are broken of 404ed

**Comment by angriman** [comment]
I fixed the link the readme and now it works, is that what you meant @alvarodemig? 
@AlexMRuch Apart from that, are there any other broken links? The links on the [website](https://networkit.github.io/) seems to work.

**Comment by AlexMRuch** [comment]
Thanks for those fixes!

On the website (https://networkit.github.io/) if you click the User Guide button in the middle of the screen (https://nbviewer.jupyter.org/url/networkit.github.io/uploads/docs/NetworKit_UserGuide.ipynb), it leads to a 404 not found error page.

Also, if you go to notebooks section of the documentation link (https://networkit.github.io/dev-docs/notebooks.html), the same happens when you click networkit user guide (https://nbviewer.jupyter.org/urls/networkit.github.io/uploads/docs/NetworKit_UserGuide.ipynb) or any other notebook (e.g., spectral clustering: https://nbviewer.jupyter.org/urls/networkit.github.io/uploads/docs/SpectralCentrality.ipynb).

Lastly, some of the Python documentation pages seem to be empty (e.g., correlation: https://networkit.github.io/dev-docs/python_api/correlation.html)

Thanks for looking into this!

**Comment by angriman** [comment]
Thanks a lot for the feedback. We fixed the broken links to the user guide also on the website.
About the documentation, there are indeed some empty pages because of missing docstrings; we will write them as soon as possible.

**Comment by AlexMRuch** [comment]
Happy to help! Very excited to see how this project continues to develop! Thanks again!
