### ISSUE TITLE
python setup.py egg_info" failed with error code

### ISSUE THREAD

**Issue by talhaanwarch** [networkit/networkit#283]
When i try to install network it, i am getting error
pip3 install networkit

python version is 3.6
I am using anaconda
error is
Command "python setup.py egg_info" failed with error code 1 in C:\Users\TALHAA~1\AppData\Local\Temp\pip-req-build-ohysrp32\

**Comment by avdgrinten** [comment]
Native windows installations are not expected to work. We recommend you to try an installation on WSL (Window Subsystem for Linux). If that does not work, please post the full output of `pip install` and we can try to reproduce the issue.

**Comment by arruda** [comment]
Hello @avdgrinten! Just wanted to point out that I'm having the same issue, and I'm using a ubuntu OS.
One thing that I believe can be the true error is this:
I'm using pipenv to install this package and it can sometimes eat up the real exception when one occurs.
When using pip to install the networkkit it is reading an error because I'm trying to install it without scipy module installed first.

```
 pip install networkit
Collecting networkit
  Downloading https://files.pythonhosted.org/packages/3c/0d/767c959cc199013e36634128fae5e77815e19d70d10743c94bf97eae3506/networkit-4.6.tar.gz (1.2MB)
    100% |████████████████████████████████| 1.2MB 7.6MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/tmp/pip-install-_wdup64l/networkit/setup_util.py", line 17, in installExternalPythonPackages
        import scipy
    ModuleNotFoundError: No module named 'scipy'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-_wdup64l/networkit/setup.py", line 29, in <module>
        installExternalPythonPackages()
      File "/tmp/pip-install-_wdup64l/networkit/setup_util.py", line 20, in installExternalPythonPackages
        installPackage('scipy')
      File "/tmp/pip-install-_wdup64l/networkit/setup_util.py", line 9, in installPackage
        pip.main(['install', package])
    AttributeError: module 'pip' has no attribute 'main'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-_wdup64l/networkit/
```
Pipenv will probably get only the final part `Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-_wdup64l/networkit/` and thus make things a bit obscure.

I'm not sure if the `pip install networkit` should be handling the scipy install or not (couldn't find the `setup_util.py` file to check what it was supposed to be doing.

And even after installing scipy, the installation (using pip) fails because it's lacking cython, so I'm starting to believe that the setup_utils is raising the exception when it doesn't find this optional libraries.

**Comment by arruda** [comment]
Also, just to give more info, I'm using the latest version of pip (18.1), but even so it looks like when the instalation is happening, the setup_utils is not using the pip version of the virtualenv where the package is to be installed (maybe it's using the system pip, which is a py2 instead of py3).
I believe this is probably the cause of all this errors, since because of this, the setup_utils is not capable of installing the necessary packages.
I'm not sure if this is a current problem in pip, pipenv, virtualenv or some crazy combination of them =/
I've solved it for now by installing all the required packages one by one, and trying again until the installation succeeded.
