### ISSUE TITLE
Wrong normalization for undirected graphs in Betweenness?

### ISSUE THREAD

**Issue by rionda** [networkit/networkit#592]
I may be wrong, but the normalization of the scores (when the `Betweenness` object is created with `normalized = true`) is not correct when the graph is undirected, due to the line:

https://github.com/networkit/networkit/blob/36a5fc57a2f6ba8d19d8fcee2c340f2434e763b6/networkit/cpp/centrality/Betweenness.cpp#L113

To see this issue, run the algorithm on the undirected graph `A - B - C` twice, once with `normalized = false` and once with `normalized = true`. The score of `B` is 2.0 both times. In the `normalized = true` case, it is obtained as 2.0 / ((2 * 1) / 2)), where the denominator is the value of the `pairs` variable (with the division by two coming from the line quoted above).

When the graph is undirected, Brandes' algorithm accounts *twice* the contribution of each *unordered* pair `(u,v)` to the non-normalized score of `w` (with `w \neq v` and `w \neq u`): one time the contribution is counted for the *ordered* pair `(u,v)`, and once for the *ordered* pair `(v,u)`. 

Thus, if one wants to get normalized scores, one should actually divide the non-normalized scores by the number of *ordered* pairs, not by the number of *unordered* pairs (which is what happens in the code right now, due to the line above).  Therefore, the factor by which one should divide is the same in both the directed and the undirected case. Thus, the line quoted above is wrong, and should be removed.

The same issue likely affects also the edge centrality (thus the whole `if (!G.isDirected())` block should be removed), but I leave that as an exercise to the reader =) .

As a side note, that `G.forNodes` can likely be a `G.parallelForNodes`. 

There is a similar issue also in the `Betweenness::maximum` function: the maximum non-normalized score in the undirected case is no different than in the directed case.

**Comment by angriman** [comment]
Fixed in #608, thanks @rionda for bringing this up.

**Comment by ramirogalvez** [comment]
I have had been obtaining different betweeness score across computers, and just realized that this is due to this comment (both of them have different networkit's versions). Now I see that at the end of @rionda comment it is stated that:

"There is a similar issue also in the Betweenness::maximum function: the maximum non-normalized score in the undirected case is no different than in the directed case."

However, when one sees the current code for Betweenness::maximum, this last bug does not seem to have been fixed (it still divides by 2). Maybe you checked this already and it was no neccesary to delete the division. But if not, I just wanted to report this issue.
