### ISSUE TITLE
Question on Aux::Random::setSeed()

### ISSUE THREAD

**Issue by rionda** [networkit/networkit#712]
https://github.com/networkit/networkit/blob/1650e788c4d1a0d0d96ef05b9dc3b04655114ab8/networkit/cpp/auxiliary/Random.cpp#L31

When should this function be used and when *must* it be used, and what is the difference between passing `true` or `false` as second argument? 
I'm wondering whether I should/must call this function with 2nd parameter `true` before entering a parallel section in which stuff like `Aux::Random::real()` is called, or maybe I should/must call this function just inside the parallel section, or.... ?

**Comment by michitux** [comment]
This function should be used when you want to ensure that the following code starts from a defined state of the (pseudo) random number generator. E.g., most randomized algorithms will produce reproducible results when the same seed is used, at least when not running in parallel.  If the function is not called, the random number generator is initialized randomly using entropy that is available from the operating system. Therefore, there exists no situation where you definitely must use this function.

NetworKit uses a (pseudo) random number generator per thread as the implementation is not thread-safe. If the second parameter is false, all of these generators are (re-)initialized using the provided seed on their next use. If the second parameter is true, the thread id is added to the seed, meaning that each thread gets a different sequence of random numbers. For example in an algorithm that samples random nodes in each thread, this could avoid that every thread samples the same nodes. You can call this function inside parallel sections, but I don't see any reason why you should, and there is definitely no need to do that. In general algorithms should not call this function internally but users should call this function, e.g., in evaluation scripts to get reproducible results. Unfortunately, many parallel algorithms in NetworKit are nondeterministic even with a fixed seed due to race conditions or nondeterministic scheduling.

I think it might be a good idea to just always set the second parameter to true and deprecate it as it seems like having the same randomness in every thread could indeed be a problem that might not be obvious to users and I do not see any use case where you would want to have the same state in every thread.

**Comment by rionda** [comment]
Thanks.
So there is no need to call this function in "normal" situations, because the per-thread PRNGs are initialized independently with different at some point, correct? If so, where/when does this initialization happen?

**Comment by michitux** [comment]
Yes, exactly. This initialization happens when the PRNG is requested for the first time in that thread at the beginning of [`getURNG()`](https://github.com/networkit/networkit/blob/1650e788c4d1a0d0d96ef05b9dc3b04655114ab8/networkit/cpp/auxiliary/Random.cpp#L60) which is called in every function that generates a random number in NetworKit. In `getSeed()`, [`getSeed_`](https://github.com/networkit/networkit/blob/1650e788c4d1a0d0d96ef05b9dc3b04655114ab8/networkit/cpp/auxiliary/Random.cpp#L38) is then called with 0 as parameter which uses [`std::random_device`](https://en.cppreference.com/w/cpp/numeric/random/random_device) to get a random number.

**Comment by rionda** [comment]
Great, thanks. This function definitively would benefit from better documentation.
