### ISSUE TITLE
Building NetworKit causes warnings about deprecated functionality

### ISSUE THREAD

**Issue by avdgrinten** [networkit/networkit#742]
Building NetworKit involves tons of warnings. This is not caught by the CI due to `-Wno-error=deprecated-declarations`. Remove all use of the deprecated functionality, then remove `-Wno-error=deprecated-declarations`.

NetworKit should never make use of its own deprecated functionality. If it has to use deprecated functions because no other alternative exists, why is that functionality deprecated?

**Comment by angriman** [comment]
The feature that triggers those warnings is the support for time steps in graphs. Time steps have been deprecated together with a bunch of features in order to clean up `Graph` in before a major refactor of the data structure. However, time steps have not been removed in #458 because they are needed by a graph generator developed by @michitux (see https://github.com/networkit/networkit/pull/458#issuecomment-712132305).

**Comment by avdgrinten** [comment]
Yes, I am aware of that. My more general comment here is that functionality should never be deprecated if it still has (non-deprecated) internal users. If there are deprecated internal users they need to work around the deprecated functions to avoid causing warnings.

In any case, building NetworKit should not cause deprecation warnings (or any other warnings) as they clutter the build output (concealing true errors) and confuse users. Right now, somebody who installs NetworKit with default CMake flags just gets a few pages of warnings, I think that's not really a desirable situation.
