### ISSUE TITLE
Install support through Poetry and atlernative build systems

### ISSUE THREAD

**Issue by t03i** [networkit/networkit#774]
Installing networkit is not yet possible through poetry. From my understanding, this is due to the encapsulated build process of poetry. Specifically, Cython support through poetry seems to be best achieved using PEP 518 and specifying build dependencies or a build script in a pyproject.toml file [1] [2]. 

Implementing PEP 518 would not only be a QoL improvement for poetry users, it could also be an initial step into adopting poetry for networkit in general. This would significantly simplify python dependency management, as well as package building and publishing.

**Comment by fabratu** [comment]
Thanks for the request and the initial research on how to get support for poetry.

We have to look into it. In reality supporting a package manager always comes with a cost in maintaining stuff. From what I read, poetry is quite popular to keep these costs low - but there is always a tradeoff in supporting more systems. It seems you can mix conda and poetry if the dependencies are not too complicated.

I will turn this in a discussion btw. - since it is not really issue, more something we could improve on.
