### ISSUE TITLE
Feature request: Topological sort

### ISSUE THREAD

**Issue by opatut** [networkit/networkit#827]
I might be struggling with the docs, or there is just no toposort algorithm available in the library? I thought that would be a pretty standard graph operation everybody needs, so could it be added? Right now I've implemented my own in Python, but I bet it could be faster ;)

```python
from collections import deque

def topological_sort(G):
    queue = deque()
    in_degrees = {}

    for n in G.iterNodes():
        d = G.degreeOut(n)
        if d > 0:
            in_degrees[n] = d
        elif d == 0:
            queue.append(n)

    while queue:
        node = queue.popleft()
        yield node

        for child in G.iterInNeighbors(node):
            in_degrees[child] -= 1

            if in_degrees[child] == 0:
                queue.append(child)
                del in_degrees[child]

    if in_degrees:
        raise ValueError("Graph contains a cycle")
```

**Comment by fabratu** [comment]
Hi,

thanks for the suggestion. For you info: I am converting this issue to a discussion (we have a category for suggesting new features).

Concerning Topo Sort: We currently use Topological-Sort as part of more complex algorithms, but it is not implemented directly. However, you can use the traversal-module (`DFS` + a `visited`-tracker) to achieve the same. Since it uses the underlying C++ core, there is likely a speed-up.

Example snippet:

```
import networkit as nk

n = 2000
p = 0.15
directed = True

G = nk.generators.ErdosRenyiGenerator(n, p, directed).generate()

def topo_sort():
    visited = [False for n in G.iterNodes()]
    result = []

    def exploreNode(u):
        visited[u] = True
        result.append(u)

    for n in G.iterNodes():
        
        if(visited[n] == False):
            nk.graph.Traversal.DFSfrom(G, n, exploreNode)

    print(len(result))
```

Cycle detection like [here](https://en.wikipedia.org/wiki/Topological_sorting) has also to be added in the end.
